package cn.ymsys.api.orm.model;

import java.io.Serializable;
import java.util.Date;

public class Attend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.ip
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.attend_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Date attendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private String openUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private String lastOpenUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Date lastOpenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attend.status
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_attend
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.id
     *
     * @return the value of t_attend.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.id
     *
     * @param id the value for t_attend.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.ip
     *
     * @return the value of t_attend.ip
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.ip
     *
     * @param ip the value for t_attend.ip
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.user_id
     *
     * @return the value of t_attend.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.user_id
     *
     * @param userId the value for t_attend.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.attend_time
     *
     * @return the value of t_attend.attend_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Date getAttendTime() {
        return attendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.attend_time
     *
     * @param attendTime the value for t_attend.attend_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setAttendTime(Date attendTime) {
        this.attendTime = attendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.open_user
     *
     * @return the value of t_attend.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public String getOpenUser() {
        return openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.open_user
     *
     * @param openUser the value for t_attend.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setOpenUser(String openUser) {
        this.openUser = openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.open_time
     *
     * @return the value of t_attend.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.open_time
     *
     * @param openTime the value for t_attend.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.last_open_user
     *
     * @return the value of t_attend.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public String getLastOpenUser() {
        return lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.last_open_user
     *
     * @param lastOpenUser the value for t_attend.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setLastOpenUser(String lastOpenUser) {
        this.lastOpenUser = lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.last_open_time
     *
     * @return the value of t_attend.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Date getLastOpenTime() {
        return lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.last_open_time
     *
     * @param lastOpenTime the value for t_attend.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setLastOpenTime(Date lastOpenTime) {
        this.lastOpenTime = lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attend.status
     *
     * @return the value of t_attend.status
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attend.status
     *
     * @param status the value for t_attend.status
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attend
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Attend other = (Attend) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAttendTime() == null ? other.getAttendTime() == null : this.getAttendTime().equals(other.getAttendTime()))
            && (this.getOpenUser() == null ? other.getOpenUser() == null : this.getOpenUser().equals(other.getOpenUser()))
            && (this.getOpenTime() == null ? other.getOpenTime() == null : this.getOpenTime().equals(other.getOpenTime()))
            && (this.getLastOpenUser() == null ? other.getLastOpenUser() == null : this.getLastOpenUser().equals(other.getLastOpenUser()))
            && (this.getLastOpenTime() == null ? other.getLastOpenTime() == null : this.getLastOpenTime().equals(other.getLastOpenTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attend
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAttendTime() == null) ? 0 : getAttendTime().hashCode());
        result = prime * result + ((getOpenUser() == null) ? 0 : getOpenUser().hashCode());
        result = prime * result + ((getOpenTime() == null) ? 0 : getOpenTime().hashCode());
        result = prime * result + ((getLastOpenUser() == null) ? 0 : getLastOpenUser().hashCode());
        result = prime * result + ((getLastOpenTime() == null) ? 0 : getLastOpenTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attend
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ip=").append(ip);
        sb.append(", userId=").append(userId);
        sb.append(", attendTime=").append(attendTime);
        sb.append(", openUser=").append(openUser);
        sb.append(", openTime=").append(openTime);
        sb.append(", lastOpenUser=").append(lastOpenUser);
        sb.append(", lastOpenTime=").append(lastOpenTime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}