package cn.ymsys.api.orm.model;

import java.io.Serializable;
import java.util.Date;

public class Blacklist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blacklist.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blacklist.user_group_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer userGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blacklist.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private String openUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blacklist.status
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blacklist.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blacklist.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Date lastOpenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blacklist.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private String lastOpenUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_blacklist
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blacklist.id
     *
     * @return the value of t_blacklist.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blacklist.id
     *
     * @param id the value for t_blacklist.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blacklist.user_group_id
     *
     * @return the value of t_blacklist.user_group_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getUserGroupId() {
        return userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blacklist.user_group_id
     *
     * @param userGroupId the value for t_blacklist.user_group_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setUserGroupId(Integer userGroupId) {
        this.userGroupId = userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blacklist.open_user
     *
     * @return the value of t_blacklist.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public String getOpenUser() {
        return openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blacklist.open_user
     *
     * @param openUser the value for t_blacklist.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setOpenUser(String openUser) {
        this.openUser = openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blacklist.status
     *
     * @return the value of t_blacklist.status
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blacklist.status
     *
     * @param status the value for t_blacklist.status
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blacklist.open_time
     *
     * @return the value of t_blacklist.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blacklist.open_time
     *
     * @param openTime the value for t_blacklist.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blacklist.last_open_time
     *
     * @return the value of t_blacklist.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Date getLastOpenTime() {
        return lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blacklist.last_open_time
     *
     * @param lastOpenTime the value for t_blacklist.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setLastOpenTime(Date lastOpenTime) {
        this.lastOpenTime = lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blacklist.last_open_user
     *
     * @return the value of t_blacklist.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public String getLastOpenUser() {
        return lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blacklist.last_open_user
     *
     * @param lastOpenUser the value for t_blacklist.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setLastOpenUser(String lastOpenUser) {
        this.lastOpenUser = lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blacklist
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Blacklist other = (Blacklist) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserGroupId() == null ? other.getUserGroupId() == null : this.getUserGroupId().equals(other.getUserGroupId()))
            && (this.getOpenUser() == null ? other.getOpenUser() == null : this.getOpenUser().equals(other.getOpenUser()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOpenTime() == null ? other.getOpenTime() == null : this.getOpenTime().equals(other.getOpenTime()))
            && (this.getLastOpenTime() == null ? other.getLastOpenTime() == null : this.getLastOpenTime().equals(other.getLastOpenTime()))
            && (this.getLastOpenUser() == null ? other.getLastOpenUser() == null : this.getLastOpenUser().equals(other.getLastOpenUser()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blacklist
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserGroupId() == null) ? 0 : getUserGroupId().hashCode());
        result = prime * result + ((getOpenUser() == null) ? 0 : getOpenUser().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOpenTime() == null) ? 0 : getOpenTime().hashCode());
        result = prime * result + ((getLastOpenTime() == null) ? 0 : getLastOpenTime().hashCode());
        result = prime * result + ((getLastOpenUser() == null) ? 0 : getLastOpenUser().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blacklist
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userGroupId=").append(userGroupId);
        sb.append(", openUser=").append(openUser);
        sb.append(", status=").append(status);
        sb.append(", openTime=").append(openTime);
        sb.append(", lastOpenTime=").append(lastOpenTime);
        sb.append(", lastOpenUser=").append(lastOpenUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}