package cn.ymsys.api.orm.model;

import java.io.Serializable;
import java.util.Date;

public class Chat implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.user_id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.chat_type
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private Integer chatType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.chat_id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private String chatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.desc
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.unread_number
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private Integer unreadNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.unread_status
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private Boolean unreadStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.open_user
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private String openUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.open_time
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.last_open_user
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private String lastOpenUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.last_open_time
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private Date lastOpenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat.status
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_chat
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.id
     *
     * @return the value of t_chat.id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.id
     *
     * @param id the value for t_chat.id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.user_id
     *
     * @return the value of t_chat.user_id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.user_id
     *
     * @param userId the value for t_chat.user_id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.chat_type
     *
     * @return the value of t_chat.chat_type
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public Integer getChatType() {
        return chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.chat_type
     *
     * @param chatType the value for t_chat.chat_type
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setChatType(Integer chatType) {
        this.chatType = chatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.chat_id
     *
     * @return the value of t_chat.chat_id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public String getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.chat_id
     *
     * @param chatId the value for t_chat.chat_id
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.desc
     *
     * @return the value of t_chat.desc
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.desc
     *
     * @param desc the value for t_chat.desc
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.unread_number
     *
     * @return the value of t_chat.unread_number
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public Integer getUnreadNumber() {
        return unreadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.unread_number
     *
     * @param unreadNumber the value for t_chat.unread_number
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setUnreadNumber(Integer unreadNumber) {
        this.unreadNumber = unreadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.unread_status
     *
     * @return the value of t_chat.unread_status
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public Boolean getUnreadStatus() {
        return unreadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.unread_status
     *
     * @param unreadStatus the value for t_chat.unread_status
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setUnreadStatus(Boolean unreadStatus) {
        this.unreadStatus = unreadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.open_user
     *
     * @return the value of t_chat.open_user
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public String getOpenUser() {
        return openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.open_user
     *
     * @param openUser the value for t_chat.open_user
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setOpenUser(String openUser) {
        this.openUser = openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.open_time
     *
     * @return the value of t_chat.open_time
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.open_time
     *
     * @param openTime the value for t_chat.open_time
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.last_open_user
     *
     * @return the value of t_chat.last_open_user
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public String getLastOpenUser() {
        return lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.last_open_user
     *
     * @param lastOpenUser the value for t_chat.last_open_user
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setLastOpenUser(String lastOpenUser) {
        this.lastOpenUser = lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.last_open_time
     *
     * @return the value of t_chat.last_open_time
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public Date getLastOpenTime() {
        return lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.last_open_time
     *
     * @param lastOpenTime the value for t_chat.last_open_time
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setLastOpenTime(Date lastOpenTime) {
        this.lastOpenTime = lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat.status
     *
     * @return the value of t_chat.status
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat.status
     *
     * @param status the value for t_chat.status
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chat other = (Chat) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getChatType() == null ? other.getChatType() == null : this.getChatType().equals(other.getChatType()))
            && (this.getChatId() == null ? other.getChatId() == null : this.getChatId().equals(other.getChatId()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getUnreadNumber() == null ? other.getUnreadNumber() == null : this.getUnreadNumber().equals(other.getUnreadNumber()))
            && (this.getUnreadStatus() == null ? other.getUnreadStatus() == null : this.getUnreadStatus().equals(other.getUnreadStatus()))
            && (this.getOpenUser() == null ? other.getOpenUser() == null : this.getOpenUser().equals(other.getOpenUser()))
            && (this.getOpenTime() == null ? other.getOpenTime() == null : this.getOpenTime().equals(other.getOpenTime()))
            && (this.getLastOpenUser() == null ? other.getLastOpenUser() == null : this.getLastOpenUser().equals(other.getLastOpenUser()))
            && (this.getLastOpenTime() == null ? other.getLastOpenTime() == null : this.getLastOpenTime().equals(other.getLastOpenTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getChatType() == null) ? 0 : getChatType().hashCode());
        result = prime * result + ((getChatId() == null) ? 0 : getChatId().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getUnreadNumber() == null) ? 0 : getUnreadNumber().hashCode());
        result = prime * result + ((getUnreadStatus() == null) ? 0 : getUnreadStatus().hashCode());
        result = prime * result + ((getOpenUser() == null) ? 0 : getOpenUser().hashCode());
        result = prime * result + ((getOpenTime() == null) ? 0 : getOpenTime().hashCode());
        result = prime * result + ((getLastOpenUser() == null) ? 0 : getLastOpenUser().hashCode());
        result = prime * result + ((getLastOpenTime() == null) ? 0 : getLastOpenTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat
     *
     * @mbggenerated Wed Aug 07 18:06:42 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", chatType=").append(chatType);
        sb.append(", chatId=").append(chatId);
        sb.append(", desc=").append(desc);
        sb.append(", unreadNumber=").append(unreadNumber);
        sb.append(", unreadStatus=").append(unreadStatus);
        sb.append(", openUser=").append(openUser);
        sb.append(", openTime=").append(openTime);
        sb.append(", lastOpenUser=").append(lastOpenUser);
        sb.append(", lastOpenTime=").append(lastOpenTime);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}