package cn.ymsys.api.orm.model;

import java.io.Serializable;

public class GroupUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_user.group_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_user.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_user.group_id
     *
     * @return the value of t_group_user.group_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_user.group_id
     *
     * @param groupId the value for t_group_user.group_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_user.user_id
     *
     * @return the value of t_group_user.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_user.user_id
     *
     * @param userId the value for t_group_user.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GroupUser other = (GroupUser) that;
        return (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}