package cn.ymsys.api.orm.model;

import java.io.Serializable;
import java.util.Date;

public class Money implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money.money
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private String openUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private String lastOpenUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_money.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private Date lastOpenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_money
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money.id
     *
     * @return the value of t_money.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money.id
     *
     * @param id the value for t_money.id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money.user_id
     *
     * @return the value of t_money.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money.user_id
     *
     * @param userId the value for t_money.user_id
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money.money
     *
     * @return the value of t_money.money
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money.money
     *
     * @param money the value for t_money.money
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money.open_user
     *
     * @return the value of t_money.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public String getOpenUser() {
        return openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money.open_user
     *
     * @param openUser the value for t_money.open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setOpenUser(String openUser) {
        this.openUser = openUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money.open_time
     *
     * @return the value of t_money.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money.open_time
     *
     * @param openTime the value for t_money.open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money.last_open_user
     *
     * @return the value of t_money.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public String getLastOpenUser() {
        return lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money.last_open_user
     *
     * @param lastOpenUser the value for t_money.last_open_user
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setLastOpenUser(String lastOpenUser) {
        this.lastOpenUser = lastOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_money.last_open_time
     *
     * @return the value of t_money.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public Date getLastOpenTime() {
        return lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_money.last_open_time
     *
     * @param lastOpenTime the value for t_money.last_open_time
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    public void setLastOpenTime(Date lastOpenTime) {
        this.lastOpenTime = lastOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Money other = (Money) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
            && (this.getOpenUser() == null ? other.getOpenUser() == null : this.getOpenUser().equals(other.getOpenUser()))
            && (this.getOpenTime() == null ? other.getOpenTime() == null : this.getOpenTime().equals(other.getOpenTime()))
            && (this.getLastOpenUser() == null ? other.getLastOpenUser() == null : this.getLastOpenUser().equals(other.getLastOpenUser()))
            && (this.getLastOpenTime() == null ? other.getLastOpenTime() == null : this.getLastOpenTime().equals(other.getLastOpenTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
        result = prime * result + ((getOpenUser() == null) ? 0 : getOpenUser().hashCode());
        result = prime * result + ((getOpenTime() == null) ? 0 : getOpenTime().hashCode());
        result = prime * result + ((getLastOpenUser() == null) ? 0 : getLastOpenUser().hashCode());
        result = prime * result + ((getLastOpenTime() == null) ? 0 : getLastOpenTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbggenerated Thu Jul 25 20:26:37 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", money=").append(money);
        sb.append(", openUser=").append(openUser);
        sb.append(", openTime=").append(openTime);
        sb.append(", lastOpenUser=").append(lastOpenUser);
        sb.append(", lastOpenTime=").append(lastOpenTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}