package cn.ymsys.api.orm.mapper;

import cn.ymsys.api.orm.model.GroupMsg;
import cn.ymsys.api.orm.model.GroupMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int countByExample(GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int deleteByExample(GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int insert(GroupMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int insertSelective(GroupMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    List<GroupMsg> selectByExample(GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    GroupMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") GroupMsg record, @Param("example") GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int updateByExample(@Param("record") GroupMsg record, @Param("example") GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int updateByPrimaryKeySelective(GroupMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_group_msg
     *
     * @mbggenerated Wed Aug 07 10:28:33 CST 2019
     */
    int updateByPrimaryKey(GroupMsg record);
}