package cn.ymsys.api.orm.mapper;

import cn.ymsys.api.orm.model.Talk;
import cn.ymsys.api.orm.model.TalkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TalkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int countByExample(TalkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int deleteByExample(TalkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int insert(Talk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int insertSelective(Talk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    List<Talk> selectByExampleWithBLOBs(TalkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    List<Talk> selectByExample(TalkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    Talk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Talk record, @Param("example") TalkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Talk record, @Param("example") TalkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int updateByExample(@Param("record") Talk record, @Param("example") TalkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int updateByPrimaryKeySelective(Talk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Talk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_talk
     *
     * @mbggenerated Wed Aug 07 09:47:54 CST 2019
     */
    int updateByPrimaryKey(Talk record);
}